from __future__ import annotations

from typing import Any, Dict, Annotated

from fastapi import APIRouter, HTTPException, Body

# Import local runtime module from parent directory
import sys
from pathlib import Path

# Add parent directory to Python path to import runtime
parent_dir = str(Path(__file__).parent.parent)
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import runtime as generated_runtime

API_SLUG = "sample_api"

router = APIRouter()

JsonPayload = Annotated[Dict[str, Any], Body(example={})]

@router.get("/orders")
async def get_orders() -> Any:
    """Autogenerated stub for GET /orders.
    Target component: OrderList.
    """
    records = generated_runtime.fetch_component_records(API_SLUG, "OrderList")
    return records

@router.get("/orders/{orderId}")
async def get_orders(*, orderId: str) -> Any:
    """Autogenerated stub for GET /orders/{orderId}.
    Target component: Order.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "Order", "id", orderId)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record
