from __future__ import annotations

from typing import Any, Dict

from fastapi import APIRouter, HTTPException

# Import local runtime module from parent directory
import sys
from pathlib import Path

# Add parent directory to Python path to import runtime
parent_dir = str(Path(__file__).parent.parent)
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import runtime as generated_runtime

API_SLUG = "twilio"

router = APIRouter()

@router.post("/2010-04-01/Accounts.json")
async def post_2010_04_01_Accounts_json(*, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts.json.
    Target component: api.v2010.account.
    """
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts.json
@router.get("/2010-04-01/Accounts/{Sid}.json")
async def get_2010_04_01_Accounts(*, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{Sid}.json.
    Target component: api.v2010.account.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{Sid}.json")
async def post_2010_04_01_Accounts(*, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{Sid}.json.
    Target component: api.v2010.account.
    """
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Addresses.json")
async def post_2010_04_01_Accounts_Addresses_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Addresses.json.
    Target component: api.v2010.account.address.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.address", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Addresses.json
# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json")
async def get_2010_04_01_Accounts_Addresses(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json.
    Target component: api.v2010.account.address.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.address", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json")
async def post_2010_04_01_Accounts_Addresses(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json.
    Target component: api.v2010.account.address.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.address", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Applications.json")
async def post_2010_04_01_Accounts_Applications_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Applications.json.
    Target component: api.v2010.account.application.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.application", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Applications.json
# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json")
async def get_2010_04_01_Accounts_Applications(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json.
    Target component: api.v2010.account.application.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.application", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json")
async def post_2010_04_01_Accounts_Applications(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json.
    Target component: api.v2010.account.application.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.application", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps/{ConnectAppSid}.json")
async def get_2010_04_01_Accounts_AuthorizedConnectApps(*, AccountSid: str, ConnectAppSid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps/{ConnectAppSid}.json.
    Target component: api.v2010.account.authorized_connect_app.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.authorized_connect_app", "id", ConnectAppSid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers.json
@router.get("/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}.json")
async def get_2010_04_01_Accounts_AvailablePhoneNumbers(*, AccountSid: str, CountryCode: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}.json.
    Target component: api.v2010.account.available_phone_number_country.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.available_phone_number_country", "id", CountryCode)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Local.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/MachineToMachine.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Mobile.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/National.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/SharedCost.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/TollFree.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Voip.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Balance.json")
async def get_2010_04_01_Accounts_Balance_json(*, AccountSid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Balance.json.
    Target component: api.v2010.account.balance.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.balance", "id", AccountSid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls.json")
async def post_2010_04_01_Accounts_Calls_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls.json.
    Target component: api.v2010.account.call.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Calls.json
# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json")
async def get_2010_04_01_Accounts_Calls(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json.
    Target component: api.v2010.account.call.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.call", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json")
async def post_2010_04_01_Accounts_Calls(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json.
    Target component: api.v2010.account.call.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Events.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Notifications/{Sid}.json")
async def get_2010_04_01_Accounts_Calls_Notifications(*, AccountSid: str, CallSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Notifications/{Sid}.json.
    Target component: api.v2010.account.call.call_notification-instance.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.call.call_notification-instance", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Notifications.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json")
async def post_2010_04_01_Accounts_Calls_Recordings_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json.
    Target component: api.v2010.account.call.call_recording.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.call_recording", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json")
async def post_2010_04_01_Accounts_Calls_Recordings(*, AccountSid: str, CallSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json.
    Target component: api.v2010.account.call.call_recording.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.call_recording", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json")
async def get_2010_04_01_Accounts_Calls_Recordings(*, AccountSid: str, CallSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json.
    Target component: api.v2010.account.call.call_recording.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.call.call_recording", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json")
async def get_2010_04_01_Accounts_Conferences(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json.
    Target component: api.v2010.account.conference.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.conference", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json")
async def post_2010_04_01_Accounts_Conferences(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json.
    Target component: api.v2010.account.conference.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.conference", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Conferences.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json")
async def post_2010_04_01_Accounts_Conferences_Recordings(*, AccountSid: str, ConferenceSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json.
    Target component: api.v2010.account.conference.conference_recording.
    """
    payload["AccountSid"] = AccountSid
    payload["ConferenceSid"] = ConferenceSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.conference.conference_recording", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json")
async def get_2010_04_01_Accounts_Conferences_Recordings(*, AccountSid: str, ConferenceSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json.
    Target component: api.v2010.account.conference.conference_recording.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.conference.conference_recording", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json")
async def get_2010_04_01_Accounts_ConnectApps(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json.
    Target component: api.v2010.account.connect_app.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.connect_app", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json")
async def post_2010_04_01_Accounts_ConnectApps(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json.
    Target component: api.v2010.account.connect_app.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.connect_app", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/ConnectApps.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Addresses/{AddressSid}/DependentPhoneNumbers.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{Sid}.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{Sid}.json.
    Target component: api.v2010.account.incoming_phone_number.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{Sid}.json")
async def get_2010_04_01_Accounts_IncomingPhoneNumbers(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{Sid}.json.
    Target component: api.v2010.account.incoming_phone_number.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.incoming_phone_number", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers.json.
    Target component: api.v2010.account.incoming_phone_number.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{Sid}.json")
async def get_2010_04_01_Accounts_IncomingPhoneNumbers_AssignedAddOns(*, AccountSid: str, ResourceSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{Sid}.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers_AssignedAddOns_json(*, AccountSid: str, ResourceSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on.
    """
    payload["AccountSid"] = AccountSid
    payload["ResourceSid"] = ResourceSid
    payload["id"] = ResourceSid
    payload["record_key"] = ResourceSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{AssignedAddOnSid}/Extensions/{Sid}.json")
async def get_2010_04_01_Accounts_IncomingPhoneNumbers_AssignedAddOns_Extensions(*, AccountSid: str, ResourceSid: str, AssignedAddOnSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{AssignedAddOnSid}/Extensions/{Sid}.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on.incoming_phone_number_assigned_add_on_extension.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_assigned_add_on.incoming_phone_number_assigned_add_on_extension", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/{ResourceSid}/AssignedAddOns/{AssignedAddOnSid}/Extensions.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Local.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Local.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers_Local_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Local.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_local.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_local", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Mobile.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Mobile.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers_Mobile_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/Mobile.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_mobile.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_mobile", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/TollFree.json
@router.post("/2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/TollFree.json")
async def post_2010_04_01_Accounts_IncomingPhoneNumbers_TollFree_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/IncomingPhoneNumbers/TollFree.json.
    Target component: api.v2010.account.incoming_phone_number.incoming_phone_number_toll_free.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.incoming_phone_number.incoming_phone_number_toll_free", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Keys/{Sid}.json")
async def get_2010_04_01_Accounts_Keys(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Keys/{Sid}.json.
    Target component: api.v2010.account.key.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.key", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Keys/{Sid}.json")
async def post_2010_04_01_Accounts_Keys(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Keys/{Sid}.json.
    Target component: api.v2010.account.key.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.key", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Keys/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Keys.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Keys.json")
async def post_2010_04_01_Accounts_Keys_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Keys.json.
    Target component: api.v2010.account.new_key.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.new_key", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Media/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Media/{Sid}.json")
async def get_2010_04_01_Accounts_Messages_Media(*, AccountSid: str, MessageSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Media/{Sid}.json.
    Target component: api.v2010.account.message.media.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.message.media", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Media.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Queues/{QueueSid}/Members/{CallSid}.json")
async def get_2010_04_01_Accounts_Queues_Members(*, AccountSid: str, QueueSid: str, CallSid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Queues/{QueueSid}/Members/{CallSid}.json.
    Target component: api.v2010.account.queue.member.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.queue.member", "id", CallSid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Queues/{QueueSid}/Members/{CallSid}.json")
async def post_2010_04_01_Accounts_Queues_Members(*, AccountSid: str, QueueSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Queues/{QueueSid}/Members/{CallSid}.json.
    Target component: api.v2010.account.queue.member.
    """
    payload["AccountSid"] = AccountSid
    payload["QueueSid"] = QueueSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.queue.member", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Queues/{QueueSid}/Members.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Messages.json")
async def post_2010_04_01_Accounts_Messages_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Messages.json.
    Target component: api.v2010.account.message.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.message", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Messages.json
# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Messages/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Messages/{Sid}.json")
async def get_2010_04_01_Accounts_Messages(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Messages/{Sid}.json.
    Target component: api.v2010.account.message.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.message", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Messages/{Sid}.json")
async def post_2010_04_01_Accounts_Messages(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Messages/{Sid}.json.
    Target component: api.v2010.account.message.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.message", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Feedback.json")
async def post_2010_04_01_Accounts_Messages_Feedback_json(*, AccountSid: str, MessageSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Messages/{MessageSid}/Feedback.json.
    Target component: api.v2010.account.message.message_feedback.
    """
    payload["AccountSid"] = AccountSid
    payload["MessageSid"] = MessageSid
    payload["id"] = MessageSid
    payload["record_key"] = MessageSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.message.message_feedback", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/SigningKeys.json")
async def post_2010_04_01_Accounts_SigningKeys_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SigningKeys.json.
    Target component: api.v2010.account.new_signing_key.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.new_signing_key", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SigningKeys.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Notifications/{Sid}.json")
async def get_2010_04_01_Accounts_Notifications(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Notifications/{Sid}.json.
    Target component: api.v2010.account.notification-instance.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.notification-instance", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Notifications.json
@router.get("/2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{Sid}.json")
async def get_2010_04_01_Accounts_OutgoingCallerIds(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{Sid}.json.
    Target component: api.v2010.account.outgoing_caller_id.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.outgoing_caller_id", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{Sid}.json")
async def post_2010_04_01_Accounts_OutgoingCallerIds(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{Sid}.json.
    Target component: api.v2010.account.outgoing_caller_id.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.outgoing_caller_id", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds.json
@router.post("/2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds.json")
async def post_2010_04_01_Accounts_OutgoingCallerIds_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/OutgoingCallerIds.json.
    Target component: api.v2010.account.validation_request.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.validation_request", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{CallSid}.json")
async def get_2010_04_01_Accounts_Conferences_Participants(*, AccountSid: str, ConferenceSid: str, CallSid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{CallSid}.json.
    Target component: api.v2010.account.conference.participant.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.conference.participant", "id", CallSid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{CallSid}.json")
async def post_2010_04_01_Accounts_Conferences_Participants(*, AccountSid: str, ConferenceSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{CallSid}.json.
    Target component: api.v2010.account.conference.participant.
    """
    payload["AccountSid"] = AccountSid
    payload["ConferenceSid"] = ConferenceSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.conference.participant", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants/{CallSid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json")
async def post_2010_04_01_Accounts_Conferences_Participants_json(*, AccountSid: str, ConferenceSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json.
    Target component: api.v2010.account.conference.participant.
    """
    payload["AccountSid"] = AccountSid
    payload["ConferenceSid"] = ConferenceSid
    payload["id"] = ConferenceSid
    payload["record_key"] = ConferenceSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.conference.participant", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Participants.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Payments.json")
async def post_2010_04_01_Accounts_Calls_Payments_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Payments.json.
    Target component: api.v2010.account.call.payments.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.payments", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Payments/{Sid}.json")
async def post_2010_04_01_Accounts_Calls_Payments(*, AccountSid: str, CallSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Payments/{Sid}.json.
    Target component: api.v2010.account.call.payments.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.payments", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Queues/{Sid}.json")
async def get_2010_04_01_Accounts_Queues(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Queues/{Sid}.json.
    Target component: api.v2010.account.queue.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.queue", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Queues/{Sid}.json")
async def post_2010_04_01_Accounts_Queues(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Queues/{Sid}.json.
    Target component: api.v2010.account.queue.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.queue", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Queues/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Queues.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Queues.json")
async def post_2010_04_01_Accounts_Queues_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Queues.json.
    Target component: api.v2010.account.queue.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.queue", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Transcriptions.json")
async def post_2010_04_01_Accounts_Calls_Transcriptions_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Transcriptions.json.
    Target component: api.v2010.account.call.realtime_transcription.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.realtime_transcription", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Transcriptions/{Sid}.json")
async def post_2010_04_01_Accounts_Calls_Transcriptions(*, AccountSid: str, CallSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Transcriptions/{Sid}.json.
    Target component: api.v2010.account.call.realtime_transcription.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.realtime_transcription", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Recordings/{Sid}.json")
async def get_2010_04_01_Accounts_Recordings(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{Sid}.json.
    Target component: api.v2010.account.recording.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.recording", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Recordings/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Recordings.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{Sid}.json")
async def get_2010_04_01_Accounts_Recordings_AddOnResults(*, AccountSid: str, ReferenceSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{Sid}.json.
    Target component: api.v2010.account.recording.recording_add_on_result.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.recording.recording_add_on_result", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{AddOnResultSid}/Payloads/{Sid}.json")
async def get_2010_04_01_Accounts_Recordings_AddOnResults_Payloads(*, AccountSid: str, ReferenceSid: str, AddOnResultSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{AddOnResultSid}/Payloads/{Sid}.json.
    Target component: api.v2010.account.recording.recording_add_on_result.recording_add_on_result_payload.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.recording.recording_add_on_result.recording_add_on_result_payload", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{AddOnResultSid}/Payloads/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{AddOnResultSid}/Payloads.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{ReferenceSid}/AddOnResults/{AddOnResultSid}/Payloads/{PayloadSid}/Data.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Recordings/{RecordingSid}/Transcriptions/{Sid}.json")
async def get_2010_04_01_Accounts_Recordings_Transcriptions(*, AccountSid: str, RecordingSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{RecordingSid}/Transcriptions/{Sid}.json.
    Target component: api.v2010.account.recording.recording_transcription.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.recording.recording_transcription", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Recordings/{RecordingSid}/Transcriptions/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Recordings/{RecordingSid}/Transcriptions.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SMS/ShortCodes/{Sid}.json")
async def get_2010_04_01_Accounts_SMS_ShortCodes(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SMS/ShortCodes/{Sid}.json.
    Target component: api.v2010.account.short_code.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.short_code", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SMS/ShortCodes/{Sid}.json")
async def post_2010_04_01_Accounts_SMS_ShortCodes(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SMS/ShortCodes/{Sid}.json.
    Target component: api.v2010.account.short_code.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.short_code", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SMS/ShortCodes.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json")
async def get_2010_04_01_Accounts_SigningKeys(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json.
    Target component: api.v2010.account.signing_key.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.signing_key", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json")
async def post_2010_04_01_Accounts_SigningKeys(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json.
    Target component: api.v2010.account.signing_key.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.signing_key", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings.json")
async def post_2010_04_01_Accounts_SIP_Domains_Auth_Calls_CredentialListMappings_json(*, AccountSid: str, DomainSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_credential_list_mapping.
    """
    payload["AccountSid"] = AccountSid
    payload["DomainSid"] = DomainSid
    payload["id"] = DomainSid
    payload["record_key"] = DomainSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_credential_list_mapping", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains_Auth_Calls_CredentialListMappings(*, AccountSid: str, DomainSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_credential_list_mapping.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_credential_list_mapping", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/CredentialListMappings/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings.json")
async def post_2010_04_01_Accounts_SIP_Domains_Auth_Calls_IpAccessControlListMappings_json(*, AccountSid: str, DomainSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_ip_access_control_list_mapping.
    """
    payload["AccountSid"] = AccountSid
    payload["DomainSid"] = DomainSid
    payload["id"] = DomainSid
    payload["record_key"] = DomainSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_ip_access_control_list_mapping", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains_Auth_Calls_IpAccessControlListMappings(*, AccountSid: str, DomainSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_ip_access_control_list_mapping.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_calls.sip_auth_calls_ip_access_control_list_mapping", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Calls/IpAccessControlListMappings/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings.json")
async def post_2010_04_01_Accounts_SIP_Domains_Auth_Registrations_CredentialListMappings_json(*, AccountSid: str, DomainSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_registrations.sip_auth_registrations_credential_list_mapping.
    """
    payload["AccountSid"] = AccountSid
    payload["DomainSid"] = DomainSid
    payload["id"] = DomainSid
    payload["record_key"] = DomainSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_registrations.sip_auth_registrations_credential_list_mapping", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains_Auth_Registrations_CredentialListMappings(*, AccountSid: str, DomainSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.sip_auth.sip_auth_registrations.sip_auth_registrations_credential_list_mapping.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_auth.sip_auth_registrations.sip_auth_registrations_credential_list_mapping", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/Auth/Registrations/CredentialListMappings/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials.json")
async def post_2010_04_01_Accounts_SIP_CredentialLists_Credentials_json(*, AccountSid: str, CredentialListSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials.json.
    Target component: api.v2010.account.sip.sip_credential_list.sip_credential.
    """
    payload["AccountSid"] = AccountSid
    payload["CredentialListSid"] = CredentialListSid
    payload["id"] = CredentialListSid
    payload["record_key"] = CredentialListSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list.sip_credential", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_CredentialLists_Credentials(*, AccountSid: str, CredentialListSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json.
    Target component: api.v2010.account.sip.sip_credential_list.sip_credential.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list.sip_credential", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json")
async def post_2010_04_01_Accounts_SIP_CredentialLists_Credentials(*, AccountSid: str, CredentialListSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json.
    Target component: api.v2010.account.sip.sip_credential_list.sip_credential.
    """
    payload["AccountSid"] = AccountSid
    payload["CredentialListSid"] = CredentialListSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list.sip_credential", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{CredentialListSid}/Credentials/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists.json")
async def post_2010_04_01_Accounts_SIP_CredentialLists_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists.json.
    Target component: api.v2010.account.sip.sip_credential_list.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_CredentialLists(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{Sid}.json.
    Target component: api.v2010.account.sip.sip_credential_list.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{Sid}.json")
async def post_2010_04_01_Accounts_SIP_CredentialLists(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{Sid}.json.
    Target component: api.v2010.account.sip.sip_credential_list.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_credential_list", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/CredentialLists/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings.json")
async def post_2010_04_01_Accounts_SIP_Domains_CredentialListMappings_json(*, AccountSid: str, DomainSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings.json.
    Target component: api.v2010.account.sip.sip_domain.sip_credential_list_mapping.
    """
    payload["AccountSid"] = AccountSid
    payload["DomainSid"] = DomainSid
    payload["id"] = DomainSid
    payload["record_key"] = DomainSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_credential_list_mapping", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains_CredentialListMappings(*, AccountSid: str, DomainSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.sip_credential_list_mapping.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_credential_list_mapping", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/CredentialListMappings/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains.json")
async def post_2010_04_01_Accounts_SIP_Domains_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains.json.
    Target component: api.v2010.account.sip.sip_domain.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json")
async def post_2010_04_01_Accounts_SIP_Domains(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json")
async def post_2010_04_01_Accounts_SIP_IpAccessControlLists_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_IpAccessControlLists(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json")
async def post_2010_04_01_Accounts_SIP_IpAccessControlLists(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json
@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_Domains_IpAccessControlListMappings(*, AccountSid: str, DomainSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json.
    Target component: api.v2010.account.sip.sip_domain.sip_ip_access_control_list_mapping.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_ip_access_control_list_mapping", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json")
async def post_2010_04_01_Accounts_SIP_Domains_IpAccessControlListMappings_json(*, AccountSid: str, DomainSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json.
    Target component: api.v2010.account.sip.sip_domain.sip_ip_access_control_list_mapping.
    """
    payload["AccountSid"] = AccountSid
    payload["DomainSid"] = DomainSid
    payload["id"] = DomainSid
    payload["record_key"] = DomainSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_domain.sip_ip_access_control_list_mapping", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json
@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json")
async def post_2010_04_01_Accounts_SIP_IpAccessControlLists_IpAddresses_json(*, AccountSid: str, IpAccessControlListSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address.
    """
    payload["AccountSid"] = AccountSid
    payload["IpAccessControlListSid"] = IpAccessControlListSid
    payload["id"] = IpAccessControlListSid
    payload["record_key"] = IpAccessControlListSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json")
async def get_2010_04_01_Accounts_SIP_IpAccessControlLists_IpAddresses(*, AccountSid: str, IpAccessControlListSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json")
async def post_2010_04_01_Accounts_SIP_IpAccessControlLists_IpAddresses(*, AccountSid: str, IpAccessControlListSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json.
    Target component: api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address.
    """
    payload["AccountSid"] = AccountSid
    payload["IpAccessControlListSid"] = IpAccessControlListSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.sip.sip_ip_access_control_list.sip_ip_address", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec.json")
async def post_2010_04_01_Accounts_Calls_Siprec_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec.json.
    Target component: api.v2010.account.call.siprec.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.siprec", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec/{Sid}.json")
async def post_2010_04_01_Accounts_Calls_Siprec(*, AccountSid: str, CallSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec/{Sid}.json.
    Target component: api.v2010.account.call.siprec.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.siprec", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams.json")
async def post_2010_04_01_Accounts_Calls_Streams_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams.json.
    Target component: api.v2010.account.call.stream.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.stream", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams/{Sid}.json")
async def post_2010_04_01_Accounts_Calls_Streams(*, AccountSid: str, CallSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams/{Sid}.json.
    Target component: api.v2010.account.call.stream.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.stream", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Tokens.json")
async def post_2010_04_01_Accounts_Tokens_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Tokens.json.
    Target component: api.v2010.account.token.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.token", payload)
    return created

@router.get("/2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json")
async def get_2010_04_01_Accounts_Transcriptions(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json.
    Target component: api.v2010.account.transcription.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.transcription", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Transcriptions.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/AllTime.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/Daily.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/LastMonth.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/Monthly.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/ThisMonth.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/Today.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/Yearly.json
# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Records/Yesterday.json
@router.get("/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json")
async def get_2010_04_01_Accounts_Usage_Triggers(*, AccountSid: str, Sid: str) -> Any:
    """Autogenerated stub for GET /2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json.
    Target component: api.v2010.account.usage.usage_trigger.
    """
    record = generated_runtime.fetch_component_record(API_SLUG, "api.v2010.account.usage.usage_trigger", "id", Sid)
    if record is None:
        raise HTTPException(status_code=404, detail="Record not found.")
    return record

@router.post("/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json")
async def post_2010_04_01_Accounts_Usage_Triggers(*, AccountSid: str, Sid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json.
    Target component: api.v2010.account.usage.usage_trigger.
    """
    payload["AccountSid"] = AccountSid
    payload["Sid"] = Sid
    payload["id"] = Sid
    payload["record_key"] = Sid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.usage.usage_trigger", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json")
async def post_2010_04_01_Accounts_Usage_Triggers_json(*, AccountSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json.
    Target component: api.v2010.account.usage.usage_trigger.
    """
    payload["AccountSid"] = AccountSid
    payload["id"] = AccountSid
    payload["record_key"] = AccountSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.usage.usage_trigger", payload)
    return created

# TODO: No operations inferred for GET /2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json
@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessages.json")
async def post_2010_04_01_Accounts_Calls_UserDefinedMessages_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessages.json.
    Target component: api.v2010.account.call.user_defined_message.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.user_defined_message", payload)
    return created

@router.post("/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions.json")
async def post_2010_04_01_Accounts_Calls_UserDefinedMessageSubscriptions_json(*, AccountSid: str, CallSid: str, payload: Dict[str, Any]) -> Any:
    """Autogenerated stub for POST /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions.json.
    Target component: api.v2010.account.call.user_defined_message_subscription.
    """
    payload["AccountSid"] = AccountSid
    payload["CallSid"] = CallSid
    payload["id"] = CallSid
    payload["record_key"] = CallSid
    created = generated_runtime.insert_component_record(API_SLUG, "api.v2010.account.call.user_defined_message_subscription", payload)
    return created

# TODO: No operations inferred for DELETE /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions/{Sid}.json
